export const TASKS_GET_SUCCESS = 'TASKS_GET_SUCCESS'
export const TASKS_POST_SUCCESS = 'TASKS_POST_SUCCESS'
export const TASKS_DELETE_SUCCESS = 'TASKS_DELETE_SUCCESS'
export const TASKS_UPDATE_SUCCESS = 'TASKS_UPDATE_SUCCESS'